// <auto-generated />
using System;
using ImmoGest.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImmoGest.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118214935_InitTables")]
    partial class InitTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ImmoGest.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("KeyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Root")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("StorageHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTimeOffset?>("UrlExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("KeyId");

                    b.HasIndex("LeaseId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("StorageHash")
                        .HasDatabaseName("IX_Attachments_StorageHash");

                    b.HasIndex("TransactionId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RIB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("Swift")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Construction")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DefaultAttachmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DefaultAttachmentId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Ice")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Rc")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Restricted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("687d9fd5-2752-4a96-93d5-0f33a49913c1"),
                            Address = "bassatine",
                            City = "tanger",
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 857, DateTimeKind.Unspecified).AddTicks(7210), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "contact@immosyncpro.com",
                            Ice = "51259111",
                            IsDeleted = false,
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 857, DateTimeKind.Unspecified).AddTicks(7211), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "IMMOSYNCPRO",
                            Phone = "0605934495",
                            Rc = "41414111",
                            Restricted = false,
                            Website = "www.immosyncpro.com"
                        });
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AvatarStorageHash")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ice")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsACompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phones")
                        .HasColumnType("json");

                    b.Property<string>("Rc")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HeroType")
                        .HasColumnType("int");

                    b.Property<string>("Individuality")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("Team")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DefaultAttachmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DefaultAttachmentId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Lease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EnableReceipts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NotificationEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotificationWhatsapp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("PaymentDate")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("PrivateNote")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("char(36)");

                    b.Property<double>("RentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("double");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("SpecialTerms")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TenancyEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TenancyStart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Maintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("ScheduledDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ScheduledDateTime");

                    b.HasIndex("Status");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.NavigationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TitleFr")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("Order");

                    b.HasIndex("ParentId");

                    b.ToTable("NavigationItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("522ddc70-62fe-4013-b0c4-1932482fd0e0"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6552), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:home",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "dashboard",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6553), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/dashboard",
                            Order = 1,
                            Title = "Dashboard",
                            TitleEn = "Dashboard",
                            TitleFr = "Tableau de bord",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("29c9a0d5-9c8a-4c11-b2ff-18e4c6dd2fd1"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6561), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:user-group",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "contacts",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6561), new TimeSpan(0, 0, 0, 0, 0)),
                            Order = 2,
                            Title = "Contacts",
                            TitleEn = "Contacts",
                            TitleFr = "Contacts",
                            Type = "collapsible"
                        },
                        new
                        {
                            Id = new Guid("3cdbc37b-6453-41d6-ae12-6560ea1ed3ac"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6563), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:user",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "tenants",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6563), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/contacts/tenants",
                            Order = 1,
                            ParentId = new Guid("29c9a0d5-9c8a-4c11-b2ff-18e4c6dd2fd1"),
                            Title = "Tenants",
                            TitleEn = "Tenants",
                            TitleFr = "Locataires",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("4fdcea05-0d1b-4de5-ab2a-c9d13201287d"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6567), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:user-circle",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "owners",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6568), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/contacts/owners",
                            Order = 2,
                            ParentId = new Guid("29c9a0d5-9c8a-4c11-b2ff-18e4c6dd2fd1"),
                            Title = "Owners",
                            TitleEn = "Owners",
                            TitleFr = "Propriétaires",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("5d797ac7-e563-4f46-8b99-2407d300e005"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6570), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:wrench-screwdriver",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "service-pros",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6570), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/contacts/service-pros",
                            Order = 3,
                            ParentId = new Guid("29c9a0d5-9c8a-4c11-b2ff-18e4c6dd2fd1"),
                            Title = "Service Providers",
                            TitleEn = "Service Providers",
                            TitleFr = "Fournisseurs de services",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("3bc9ea05-fbf9-4267-ae75-0e00f641639c"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6572), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:building-office-2",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "properties",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6572), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/property",
                            Order = 3,
                            Title = "Properties",
                            TitleEn = "Properties",
                            TitleFr = "Propriétés",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("c93b4721-4a3d-436f-ad65-ec6af2d0ddaa"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6574), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:building-office",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "buildings",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6574), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/building",
                            Order = 4,
                            Title = "Buildings",
                            TitleEn = "Buildings",
                            TitleFr = "Bâtiments",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("77f07ae3-4dc4-4c9a-ad9b-eac15438b287"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6589), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:key",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "keys",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6589), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/keys",
                            Order = 5,
                            Title = "Keys",
                            TitleEn = "Keys",
                            TitleFr = "Clés",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("92153c46-5264-4067-936f-dcb65fe0decb"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6591), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:document-text",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "leasing",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6592), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/leasing",
                            Order = 6,
                            Title = "Leasing",
                            TitleEn = "Leasing",
                            TitleFr = "Location",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("44f213ba-a62b-4667-883c-6567ce45d61b"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6593), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:calendar",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "reservations",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6594), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/reservation",
                            Order = 7,
                            Title = "Reservations",
                            TitleEn = "Reservations",
                            TitleFr = "Réservations",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("c6e1d9a8-894d-4ca2-85a4-3bc9cdaa9e92"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6598), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:folder",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "file-manager",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6598), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/gestionnaire-fichiers",
                            Order = 8,
                            Title = "File Manager",
                            TitleEn = "File Manager",
                            TitleFr = "Gestionnaire de fichiers",
                            Type = "basic"
                        },
                        new
                        {
                            Id = new Guid("fe0df833-b71d-4610-b2f9-1c681d5f9673"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6600), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "heroicons_outline:cog-6-tooth",
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = "settings",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(6600), new TimeSpan(0, 0, 0, 0, 0)),
                            Link = "/settings",
                            Order = 9,
                            Title = "Settings",
                            TitleEn = "Settings",
                            TitleFr = "Paramètres",
                            Type = "basic"
                        });
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<float>("Area")
                        .HasColumnType("float");

                    b.Property<float>("Bathrooms")
                        .HasColumnType("float");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DefaultAttachmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Equipment")
                        .HasColumnType("longtext");

                    b.Property<string>("Features")
                        .HasColumnType("longtext");

                    b.Property<bool>("Furnished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublicAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReservationShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("Pieces")
                        .HasColumnType("float");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<int>("TypePaiment")
                        .HasColumnType("int");

                    b.Property<string>("TypeProperty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("DefaultAttachmentId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfNights")
                        .HasColumnType("int");

                    b.Property<string>("PrivateNote")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AmenitiesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoriesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PropertyTypesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Settings_CompanyId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Settings_IsDeleted");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ce74ce2-0d7c-4c0d-954d-ac4e427cc539"),
                            AmenitiesJson = "[\"Parking\",\"Laundry\",\"Air conditioning\",\"Heating\",\"Swimming pool\",\"Gym\",\"Security\",\"Elevator\",\"Balcony\",\"Garden\",\"Garage\",\"Pet friendly\"]",
                            CategoriesJson = "[{\"Key\":\"location\",\"Reference\":\"AL\"},{\"Key\":\"vente\",\"Reference\":\"AV\"},{\"Key\":\"vacance\",\"Reference\":\"VC\"}]",
                            CompanyId = "687d9fd5-2752-4a96-93d5-0f33a49913c1",
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(8715), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultCity = "Tanger",
                            FeaturesJson = "[\"Alarm\",\"Furnished\",\"Renovated\",\"Hardwood floors\",\"Fireplace\",\"Fresh paint\",\"Dishwasher\",\"Walk-in closets\",\"Balcony, Deck, Patio\",\"Internet\",\"Fenced yard\",\"Tile\",\"Carpet\",\"Storage\",\"Unfurnished\"]",
                            IsDeleted = false,
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 866, DateTimeKind.Unspecified).AddTicks(8196), new TimeSpan(0, 0, 0, 0, 0)),
                            PropertyTypesJson = "[\"Residential\",\"Commercial\",\"Industrial\",\"Mixed Use\",\"Vacation Rental\",\"Investment Property\",\"Luxury\",\"Affordable Housing\",\"Student Housing\",\"Senior Living\",\"Retail Space\",\"Office Space\",\"Warehouse\",\"Land\"]"
                        });
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ExpenseType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OtherContactName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Payments")
                        .HasColumnType("json");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RevenueType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("LeaseId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("687d9fd5-2752-4a96-93d5-0f33a49913c1"),
                            CompanyId = new Guid("687d9fd5-2752-4a96-93d5-0f33a49913c1"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 639, DateTimeKind.Unspecified).AddTicks(8388), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@admin.com",
                            IsDeleted = false,
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 639, DateTimeKind.Unspecified).AddTicks(8390), new TimeSpan(0, 0, 0, 0, 0)),
                            Password = "$2a$11$Ut.2OKEIOMrThj.Ievp7sOBOg2t7vIqvplhNXYzT9F709IOeOsLty",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("687d9fd5-2752-4a96-93d5-0f33a49913c2"),
                            CompanyId = new Guid("687d9fd5-2752-4a96-93d5-0f33a49913c1"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 749, DateTimeKind.Unspecified).AddTicks(6363), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user@boilerplate.com",
                            IsDeleted = false,
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 749, DateTimeKind.Unspecified).AddTicks(6366), new TimeSpan(0, 0, 0, 0, 0)),
                            Password = "$2a$11$VhEjq3yY74DDcL3jV2N8yeAcf406l1nauac2i0n.he4FCX/puxch.",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.UserPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("787d9fd5-2752-4a96-93d5-0f33a49913c1"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 868, DateTimeKind.Unspecified).AddTicks(1003), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 868, DateTimeKind.Unspecified).AddTicks(996), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionsJson = "{\n                        \"dashboard\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"properties\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"buildings\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"leasing\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"reservations\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"maintenance\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"contacts\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"keys\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"banks\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"payments\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"file-manager\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"reports\": {\"view\": true, \"edit\": true, \"delete\": true},\n                        \"settings\": {\"view\": true, \"edit\": true, \"delete\": true}\n                    }",
                            UserId = new Guid("687d9fd5-2752-4a96-93d5-0f33a49913c1")
                        },
                        new
                        {
                            Id = new Guid("787d9fd5-2752-4a96-93d5-0f33a49913c2"),
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 868, DateTimeKind.Unspecified).AddTicks(1007), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedOn = new DateTimeOffset(new DateTime(2025, 11, 18, 21, 49, 34, 868, DateTimeKind.Unspecified).AddTicks(1004), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionsJson = "{\n                        \"dashboard\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"properties\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"buildings\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"leasing\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"reservations\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"maintenance\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"contacts\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"keys\": {\"view\": false, \"edit\": false, \"delete\": false},\n                        \"banks\": {\"view\": false, \"edit\": false, \"delete\": false},\n                        \"payments\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"file-manager\": {\"view\": true, \"edit\": false, \"delete\": false},\n                        \"reports\": {\"view\": false, \"edit\": false, \"delete\": false},\n                        \"settings\": {\"view\": false, \"edit\": false, \"delete\": false}\n                    }",
                            UserId = new Guid("687d9fd5-2752-4a96-93d5-0f33a49913c2")
                        });
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Contact", "Contact")
                        .WithMany("Attachments")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Lease", "Lease")
                        .WithMany("Attachments")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Attachments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Attachments")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");

                    b.Navigation("Key");

                    b.Navigation("Lease");

                    b.Navigation("Property");

                    b.Navigation("Reservation");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Bank", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Building", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Attachment", "DefaultAttachment")
                        .WithMany()
                        .HasForeignKey("DefaultAttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("DefaultAttachment");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Contact", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Key", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Attachment", "DefaultAttachment")
                        .WithMany()
                        .HasForeignKey("DefaultAttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Property", "Property")
                        .WithMany("Keys")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultAttachment");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Lease", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Property", "Property")
                        .WithMany("Leases")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Maintenance", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Property", "Property")
                        .WithMany("Maintenances")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.NavigationItem", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.NavigationItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Property", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Building", "Building")
                        .WithMany("Properties")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Attachment", "DefaultAttachment")
                        .WithMany()
                        .HasForeignKey("DefaultAttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("DefaultAttachment");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoGest.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ImmoGest.Domain.Entities.Lease", "Lease")
                        .WithMany()
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImmoGest.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Lease");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.User", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.UserPermissions", b =>
                {
                    b.HasOne("ImmoGest.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Building", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Contact", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Lease", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.NavigationItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Property", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Leases");

                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("ImmoGest.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
